"""
Example usage of the Coding Agent
Esempio di utilizzo del Coding Agent
"""

from coding_agent import CodingAgent


def main():
    """Demonstrate the coding agent capabilities."""
    
    print("=" * 60)
    print("CODING AGENT DEMO / DEMO AGENTE DI CODIFICA")
    print("=" * 60)
    
    # Create an instance of the coding agent
    agent = CodingAgent("HAMong Demo Agent")
    
    # Example 1: Generate different types of code
    print("\n1. CODE GENERATION / GENERAZIONE CODICE\n")
    
    print("--- Python Hello World ---")
    code = agent.generate_code("hello world", "python")
    print(code)
    
    print("\n--- JavaScript Function ---")
    code = agent.generate_code("function", "javascript")
    print(code)
    
    print("\n--- Java Class ---")
    code = agent.generate_code("class", "java")
    print(code)
    
    # Example 2: Analyze the coding agent itself
    print("\n\n2. CODE ANALYSIS / ANALISI CODICE\n")
    
    print("--- Analyzing coding_agent.py ---")
    analysis = agent.analyze_file("coding_agent.py")
    
    if "error" not in analysis:
        print(f"📄 File: {analysis['filename']}")
        print(f"📏 Lines of code: {analysis['line_count']}")
        print(f"📝 Character count: {analysis['char_count']}")
        print(f"💬 Has comments: {analysis['has_comments']}")
        print(f"🔧 Functions found: {analysis['functions']}")
        print(f"\n💡 Suggestions / Suggerimenti:")
        for i, suggestion in enumerate(analysis['suggestions'], 1):
            print(f"   {i}. {suggestion}")
    else:
        print(f"❌ Error: {analysis['error']}")
    
    # Example 3: Create and analyze a sample file
    print("\n\n3. CREATE AND ANALYZE NEW FILE / CREA E ANALIZZA NUOVO FILE\n")
    
    # Generate some code
    sample_code = agent.generate_code("hello world", "python")
    
    # Save it to a file
    with open("sample_generated.py", "w") as f:
        f.write("# Generated by HAMong Coding Agent\n")
        f.write("# Generato da HAMong Coding Agent\n\n")
        f.write(sample_code)
    
    print("✅ Created sample_generated.py")
    
    # Analyze the new file
    print("\n--- Analyzing sample_generated.py ---")
    analysis = agent.analyze_file("sample_generated.py")
    
    if "error" not in analysis:
        print(f"📄 File: {analysis['filename']}")
        print(f"📏 Lines of code: {analysis['line_count']}")
        print(f"💬 Has comments: {analysis['has_comments']}")
        print(f"\n💡 Suggestions / Suggerimenti:")
        for i, suggestion in enumerate(analysis['suggestions'], 1):
            print(f"   {i}. {suggestion}")
    
    # Example 4: Show help
    print("\n\n4. AGENT HELP / AIUTO AGENTE\n")
    print(agent.help())
    
    print("\n" + "=" * 60)
    print("Demo completed! / Demo completata!")
    print("=" * 60)


if __name__ == "__main__":
    main()
