"""
Interactive Coding Agent Demo
Demo interattiva del Coding Agent

This script demonstrates interactive usage of the coding agent.
Questo script dimostra l'uso interattivo dell'agente di codifica.
"""

from coding_agent import CodingAgent
import os


def print_separator(title=""):
    """Print a nice separator with optional title."""
    if title:
        print(f"\n{'=' * 60}")
        print(f" {title}")
        print('=' * 60)
    else:
        print('-' * 60)


def demo_code_generation():
    """Demonstrate code generation capabilities."""
    print_separator("CODE GENERATION DEMO / DEMO GENERAZIONE CODICE")
    
    agent = CodingAgent()
    
    examples = [
        ("Python", "hello world", "python"),
        ("JavaScript", "function", "javascript"),
        ("Java", "class", "java"),
        ("C++", "hello world", "cpp"),
    ]
    
    for lang, desc, lang_code in examples:
        print(f"\n🔹 Generating {desc} in {lang}:")
        print_separator()
        code = agent.generate_code(desc, lang_code)
        print(code)


def demo_file_analysis():
    """Demonstrate file analysis capabilities."""
    print_separator("FILE ANALYSIS DEMO / DEMO ANALISI FILE")
    
    agent = CodingAgent()
    
    # Analyze the coding_agent.py file
    files_to_analyze = ["coding_agent.py", "example_usage.py"]
    
    for filepath in files_to_analyze:
        if os.path.exists(filepath):
            print(f"\n📁 Analyzing: {filepath}")
            print_separator()
            
            analysis = agent.analyze_file(filepath)
            
            if "error" not in analysis:
                print(f"  📄 Filename: {analysis['filename']}")
                print(f"  📏 Lines: {analysis['line_count']}")
                print(f"  📝 Characters: {analysis['char_count']}")
                print(f"  💬 Has comments: {'✓' if analysis['has_comments'] else '✗'}")
                print(f"  🔧 Functions: {analysis['functions']}")
                print(f"\n  💡 Suggestions:")
                for i, suggestion in enumerate(analysis['suggestions'], 1):
                    print(f"     {i}. {suggestion}")
            else:
                print(f"  ❌ {analysis['error']}")


def create_sample_files():
    """Create sample files to demonstrate analysis."""
    print_separator("CREATING SAMPLE FILES / CREAZIONE FILE DI ESEMPIO")
    
    agent = CodingAgent()
    
    # Create a directory for samples
    os.makedirs("examples", exist_ok=True)
    
    samples = [
        ("examples/hello.py", "hello world", "python"),
        ("examples/utils.js", "function", "javascript"),
        ("examples/Person.java", "class", "java"),
    ]
    
    for filepath, desc, lang in samples:
        code = agent.generate_code(desc, lang)
        with open(filepath, "w") as f:
            f.write(f"// Generated by HAMong Coding Agent\n")
            f.write(f"// Generato da HAMong Coding Agent\n\n")
            f.write(code)
        print(f"✅ Created: {filepath}")
    
    print("\n📂 Sample files created in 'examples/' directory")
    print("   File di esempio creati nella directory 'examples/'")


def analyze_sample_files():
    """Analyze the created sample files."""
    print_separator("ANALYZING SAMPLE FILES / ANALISI FILE DI ESEMPIO")
    
    agent = CodingAgent()
    examples_dir = "examples"
    
    if not os.path.exists(examples_dir):
        print("❌ Examples directory not found. Run create_sample_files() first.")
        return
    
    for filename in os.listdir(examples_dir):
        filepath = os.path.join(examples_dir, filename)
        if os.path.isfile(filepath):
            print(f"\n📝 {filename}")
            print_separator()
            
            analysis = agent.analyze_file(filepath)
            if "error" not in analysis:
                print(f"  Lines: {analysis['line_count']}")
                print(f"  Has comments: {'Yes' if analysis['has_comments'] else 'No'}")
                print(f"  Functions: {analysis['functions']}")
                
                if analysis['suggestions']:
                    print(f"  Suggestions:")
                    for suggestion in analysis['suggestions']:
                        print(f"    • {suggestion}")


def show_agent_capabilities():
    """Show all agent capabilities."""
    print_separator("AGENT CAPABILITIES / CAPACITÀ DELL'AGENTE")
    
    agent = CodingAgent("HAMong Interactive Agent")
    print(agent.help())


def main():
    """Run the interactive demo."""
    print("\n" + "=" * 60)
    print(" HAMong CODING AGENT - INTERACTIVE DEMO")
    print(" AGENTE DI CODIFICA HAMong - DEMO INTERATTIVA")
    print("=" * 60)
    
    # Show capabilities
    show_agent_capabilities()
    
    # Demo code generation
    demo_code_generation()
    
    # Demo file analysis
    demo_file_analysis()
    
    # Create and analyze sample files
    create_sample_files()
    analyze_sample_files()
    
    print("\n" + "=" * 60)
    print(" 🎉 Interactive demo completed!")
    print(" 🎉 Demo interattiva completata!")
    print("=" * 60)
    print("\n💡 Tip / Suggerimento:")
    print("   You can import and use CodingAgent in your own scripts!")
    print("   Puoi importare e usare CodingAgent nei tuoi script!\n")


if __name__ == "__main__":
    main()
